### PR TITLE
feat: added ability to generate doc

### PR DESCRIPTION
**Pull request by ankitverma2211**
Closes : #9 

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/falso/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

This PR adds ability to generate doc using typedoc

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
By Running the command npm run doc we will be able to auto-generate doc for our code 

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by ankitverma2211** [comment]
@NetanelBasal let me know your input and if I need to make any chnages

**Comment by NetanelBasal** [comment]
It seems fine. We are going to merge a significant change soon. You can start adding the doc's comments after it.

**Comment by ankitverma2211** [comment]
@NetanelBasal it's ready for review please review it.

**Comment by NetanelBasal** [comment]
Thanks for the PR. I was rethinking it, and I prefer a more amicable solution. See https://github.com/ngneat/falso/issues/30

**Pull request closed without merging**
