### PR TITLE
randChanceBoolean

### PR DESCRIPTION
**Pull request by PumpedSardines**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/ngneat/falso/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
Issue described in #306 
```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by PumpedSardines** [comment]
Hmm something seems to have happen with the git history

**Comment by NetanelBasal** [comment]
Can you reopen it, please?

**Comment by PumpedSardines** [comment]
What do you mean by reopen? @NetanelBasal

**Comment by NetanelBasal** [comment]
You have 600 commits for some reason:)

**Comment by NetanelBasal** [comment]
Screen Shot 2022-11-01 at 15 03 21

**Comment by PumpedSardines** [comment]
#332 fixes the git history... Not sure what happened :)

**Pull request closed without merging**
