### PR TITLE
feat: 🔥 Replace accented chars in email addresses

### PR DESCRIPTION
**Pull request by theryansmee**
Add core string manipulation function to replace accented chars with
regular ones. Move capitalize first lettercapitalizeFirstLetter to string-manipulation

✅ Closes: #153 

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/falso/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Emails can contain accented characters

Issue Number: #153

## What is the new behaviour?
Accented names can be passed to `randEmail` but any accented characters will be replaced. This allows for real world scenarios such as a `randUser` having names with special characters but emails without.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Remind me why do we need the accent?

**Comment by theryansmee** [comment]
@NetanelBasal it's very common to have accented names around Europe, so it think it's good to have test data that ensures your code doesn't fall over when it encounters them 😊 

(I hadn't actually realised that they were not valid in emails, otherwise I would have sorted this previously)

**Comment by theryansmee** [comment]
Im happy to add a similar option to `randUser` as we have in rand first and last name, to give users the option to not have them? 

It's almost no work to implement

**Comment by NetanelBasal** [comment]
I see, but I'm worried about the performance of this.

**Comment by NetanelBasal** [comment]
Maybe we can separate them to another dataset and use them in the proper function.

**Comment by theryansmee** [comment]
@NetanelBasal I was a little worried but it didn't actually seem to noticeably impact on a few quick tests I did.

The names are already separated, so we could change `randUser` & `randEmail` to only use the names without accents. (`{ withAccents: false }`)

If a user passed a first/last name with accented letters, we could error or just strip them out (rather than replace). 

E.G

```js
randEmail({ firstName: 'Netánel', lastName: 'Basäl' });
// netnel.basl@gmail.con
```

**Comment by theryansmee** [comment]
It's not perfect, but it handles the performance issues 😊

**Comment by NetanelBasal** [comment]
Yes, I meant when generating big arrays. I'd go with your suggestion but I don't think it's required to add the protection.

**Comment by theryansmee** [comment]
Ok cool, I'll get that changed when I finish work today. 

Are you ok with `core/text-manipulation.ts` for string methods? Or would you prefer me to move the capitalizeFirstLetter function back until we have more shared methods?

**Comment by NetanelBasal** [comment]
The latter

**Pull request merged**
