### PR TITLE
docs(stackblitz): update link with new version

### LINKED ISSUE #287: Create falso.new on stackblitz
### Description

Create a playground environment on stackblitz using the `falso.new` domain:

https://developer.stackblitz.com/docs/guide/open-from-github#set-up-the-main-starter-url

See [faker.js]([fakerjs.dev/new](https://fakerjs.dev/new)) example.

### Proposed solution

_No response_

### Alternatives considered

_No response_

### Do you want to create a pull request?

No

### PR DESCRIPTION
**Pull request by Naaajii**
fixes #287

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/falso/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

updates stackblitz link in readme.md file

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

- Issue Number: #287

## What is the new behavior?

updated stackblitz link

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by ChanhyukPark-Tech — APPROVED** [review]
awesome😃

**Review by ChanhyukPark-Tech — APPROVED** [review]
awesome😃

**Review by ChanhyukPark-Tech — APPROVED** [review]
awesome😃

**Comment by Naaajii** [comment]
so can it be merged? :D

**Comment by shaharkazaz** [comment]
@Naaajii thanks for the PR!
I tried opening the SB but the page won't load, not sure if it's an issue with SB itself or the project, can you please check?
Also, I saw that there are 3 imports from the transloco lib any reason why they are not united?

**Comment by Naaajii** [comment]
@shaharkazaz mmm, not sure bout the why the isn't page loading, it seem to be loading & showing data from library - [here's an image.](https://github.com/ngneat/falso/assets/54370141/18366c21-6b29-4efa-a683-59652abea53d) Unless, I'm missing something.

about 3 imports, it was just preference actually - I have updated the SB & imported them in single line now. :tada:

**Comment by shaharkazaz** [comment]
@Naaajii seems to be working, might have been something in my network 🤷‍♂️

**Pull request merged**
