### PR TITLE
chore: fix npm test script and github action

### PR DESCRIPTION
**Pull request by iamandrewluca**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/falso/blob/master/CONTRIBUTING.md#commit

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

GitHub action is running `npm run test`, but `test` script is just echoing text

## What is the new behavior?

`npm run test` will run actual nx test comand

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by geromegrignon** [comment]
Thank you!

I'm so used to add it on projects with built-in scripts, I forgot to check the package.json!

**Comment by NetanelBasal** [comment]
I already did it :) Thanks

**Comment by NetanelBasal** [comment]
@iamandrewluca I'm wondering why workspaces didn't work here - https://github.com/ngneat/falso/runs/4781027215?check_suite_focus=true

**Comment by iamandrewluca** [comment]
@NetanelBasal npm workspaces work from npm@7, use node@16 in action that comes with npm@7+

if you want to keep node@14, you will need manually to `cd` into falso folder and install dependencies

see: https://github.com/ngneat/falso/pull/24/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR13

**Comment by NetanelBasal** [comment]
Let's try node 16

**Comment by iamandrewluca** [comment]
@NetanelBasal what tool are you using for release/publish?

would be nice to have a script in package.json for that

**Comment by NetanelBasal** [comment]
I prefer to do it manually to avoid bot mistakes.

**Comment by NetanelBasal** [comment]
changelog is done via the standard release package.

**Pull request closed without merging**
