### PR TITLE
feat: 🔥 allow date strings for betweenDate

### PR DESCRIPTION
**Pull request by mr-short**
Allow date strings for betweenDate

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/falso/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

`betweenDate` only allows Date objects

Issue Number: N/A

## What is the new behavior?

`betweenDate` now accepts strings as well, which then is converted to Dates automatically

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by NetanelBasal** [comment]
@mr-short ci is failing.

**Comment by mr-short** [comment]
>  ci is failing.

@NetanelBasal It is an unrelated test, I only modified dates.

```
FAIL src/tests/full-name.spec.ts
  ● fullName › withAccents is passed › withAccents is true › should return a string with a first name, a space and then last name

    expect(received).toMatch(expected)

    Expected pattern: /^[a-zA-ZāĀàÀáÁâÂãÃäÄÅåæÆçÇčČćĆðÐēĒèÈéÉêÊĚěëËėĖìÌíÍîÎïÏłŁñÑńŃōŌøØòÒóÓôÔõÕöÖőŐœŒřŘšŠßÞþùÙúÚûÛūŪüÜýÝÿŸžŽżŻ]+(\-[a-zA-ZāĀàÀáÁâÂãÃäÄÅåæÆçÇčČćĆðÐēĒèÈéÉêÊĚěëËėĖìÌíÍîÎïÏłŁñÑńŃōŌøØòÒóÓôÔõÕöÖőŐœŒřŘšŠßÞþùÙúÚûÛūŪüÜýÝÿŸžŽżŻ]+)?\s[a-zA-ZāĀàÀáÁâÂãÃäÄÅåæÆçÇčČćĆðÐēĒèÈéÉêÊĚěëËėĖìÌíÍîÎïÏłŁñÑńŃōŌøØòÒóÓôÔõÕöÖőŐœŒřŘšŠßÞþùÙúÚûÛūŪüÜýÝÿŸžŽżŻ]+(\-[a-zA-ZāĀàÀáÁâÂãÃäÄÅåæÆçÇčČćĆðÐēĒèÈéÉêÊĚěëËėĖìÌíÍîÎïÏłŁñÑńŃōŌøØòÒóÓôÔõÕöÖőŐœŒřŘšŠßÞþùÙúÚûÛūŪüÜýÝÿŸžŽżŻ]+)?$/
    Received string:  "Caroline Van-der-Heijden"
```

**Comment by NetanelBasal** [comment]
@theryansmee ?

**Comment by theryansmee** [comment]
> should return a string with a first name, a space and then last name

@NetanelBasal Hello mate,  I'll get this fixed. I'm not sure why this hasn't failed before.

**Pull request merged**
