### PR TITLE
feat: 🔥 build locales

### PR DESCRIPTION
**Pull request by michaelxvoelker**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/falso/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #1 

## What is the new behavior?

The `build-locales` target can build all locales under `packages/falso/src/lib/locales` folder.  Only a barrel file per locale (`ru/index.ts`, es/index.ts`, etc.) is required.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by michaelxvoelker** [comment]
Not sure about the build errors.

I also can't run the normal build, without adding `seedrandom` and `uuid` to the root `package.json` 🤔

**Comment by michaelxvoelker** [comment]
The `build-locales` target can build all locales under `packages/falso/src/lib/locales` folder. Only a barrel file per locale (`ru/index.ts`, `es/index.ts`, etc.) is required.

The result would have the respective locales as secondary entry points: 
image

**Comment by michaelxvoelker** [comment]
The locales src folder and output folder can be configured through target options in `project.json`:
```json
    "build-locales": {
      "executor": "./tools/executors/build-locales:build-locales",
      "options": {
        "localesOutputPath": "dist/packages/falso/locales",
        "falsoSourcePath": "packages/falso/src",
        "localesSourcePath": "packages/falso/src/lib/locales"
      }
    },
```

**Comment by michaelxvoelker** [comment]
The `build-locales` target would build all locales:
image

**Comment by NetanelBasal** [comment]
Thanks. Looks good. I have a few questions:

- Have you tested it using `npm link`?
- The goal is to make this process automatic by marking the files we want to translate with the `.i18n` extension (e.g. `word.i18n.json`). Then we can copy the corresponding typescript file and translate the data using an automated tool or manually. What do you think about it?

**Comment by michaelxvoelker** [comment]
* I have tested it with a local npm registry using verdaccio. I will do another test with `npm link` 
* This increment is currently only about the build process. It requires the translated data and typescript files, already be in place. I thought, maybe the `translate` executor is capable of doing the translation part? But I can also have a look into that and adapt if necessary. 😊

Though I have questions regarding the translation:
* The goal is that the translations are also stored in the repository, right? 
* Would we allow to push new generators without translations, even if they are supposed to be translated?
* If yes, should the automatic translation kick in in such cases and provide an automated translation, as part of the CI?

**Comment by NetanelBasal** [comment]
> The goal is that the translations are also stored in the repository, right?
Yes

> Would we allow to push new generators without translations, even if they are supposed to be translated?
Yes, we can't enforce contributors to provide localized versions.

> If yes, should the automatic translation kick in in such cases and provide an automated translation, as part of the CI?

It'll be great if we can use something like Microsoft translate service ( Google translate has limitations). We can start with manual translations and automate them in separate PR. In the meantime, I'd add what I suggested with the `i18n` extension and copy the typescript file.

**Comment by michaelxvoelker** [comment]
Sounds good. I would love to automate the translations in a separate PR. 👍 

Do you have a list of languages on your mind, that we want to start with?

**Comment by NetanelBasal** [comment]
https://www.berlitz.com/en-uy/blog/most-spoken-languages-world

**Comment by NetanelBasal** [comment]
You can choose 5 from here and yours :)

**Comment by michaelxvoelker** [comment]
Using the package with `npm link` worked seamlessly. 

I also added the `randBird` translations and introduced the `*.i18n.json` pattern.

**Comment by NetanelBasal** [comment]
@michaelxvoelker, thanks for the great work. We need to do the following:

- Copy the typescript file from the main locale so it'll be the single source of truth. 
- Mark the files we want to translate and run a script that uses a translation service.

**Comment by NetanelBasal** [comment]
image

And we should remove the i18n folder with the types after build

**Comment by NetanelBasal** [comment]
@michaelxvoelker, instead of copying the typescript file, it'll be better to think about a way we can use the original with data we load from a locale file.

**Comment by NetanelBasal** [comment]
One suggestion:

```ts

import { FakeOptions, fake } from './core/core';
import { data } from './bird.i18n.json';

/**
 * Generate a random bird.
 *
 * @category animals
 *
 * @example
 *
 * randBird()
 *
 * @example
 *
 * randBird({ length: 10 })
 *
 */
export function randBird<Options extends FakeOptions = never>(
  options?: Options
) {
  return fake(options.locale ?? data, options);
}

```

The consumer:

```ts
import { randBird, useLocale } from '@ngneat/falso';
import ruBird from '@ngneat/falso/i18n/ru/bird';

randBird({ locale })
```

**Comment by michaelxvoelker** [comment]
I have an idea, will try it out.

**Comment by michaelxvoelker** [comment]
I'm not sure about this:

>import { randBird, useLocale } from '@ngneat/falso';
>import ruBird from '@ngneat/falso/i18n/ru/bird';
>
>randBird({ locale })

Do you mean:
```ts
import { randBird } from '@ngneat/falso';
import ruBird from '@ngneat/falso/i18n/ru/bird';

randBird({ locale: ruBird })
```

I like the idea. So far, the `data` was an implementation detail and not even typed. I'm a bit worried about adding it to the API. 🤔  What do you think?

**Comment by NetanelBasal** [comment]
What else can we do?

**Comment by michaelxvoelker** [comment]
Hmm, for now probably not much without losing tree shakeability. 

Anyways, it's not a blocker. I will provide an initial implementation, as proposed. 😊

**Comment by NetanelBasal** [comment]
Cool, thanks.

**Comment by iamandrewluca** [comment]
:eyes: Any way to use for example [fileReplacements](https://nx.dev/web/build#filereplacements) option to switch locales before each locale build, instead of duplicating code? 🤔

**Comment by NetanelBasal** [comment]
With this suggestion, what happens if you import a locale in your application? You'll have two copied versions of the randBird function?

**Comment by iamandrewluca** [comment]
True 🙂

**Comment by NetanelBasal** [comment]
The goal is to avoid this :)

**Comment by NetanelBasal** [comment]
@michaelxvoelker any news here :) ?

**Pull request merged**
