### PR TITLE
feat: 🔥 Add food from LATAM

### PR DESCRIPTION
**Pull request by midudev**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/falso/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Getting random food from anywhere but LATAM.

## What is the new behavior?

Add food from LATAM

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by rodrigo-funes-biasatti** [comment]
Nice feat

**Comment by jsrubianoj** [comment]
This is urgently needed!

**Comment by rroblf01** [comment]
These are the necessary changes to be able to use this library correctly.

**Comment by josuerodcat90** [comment]
Please add as soon as you can ❤️🙏🏻

**Comment by NetanelBasal** [comment]
Check CI, please. It needs to use `seed`.

**Comment by leonardofrp5** [comment]
> 

@midudev

**Comment by leonardofrp5** [comment]
Great PR for LATAM 🔥

**Comment by theryansmee** [comment]
@midudev - This is a great PR! 
The tests I wrote are a little less dynamic than I'd of liked, so when you add new items to the json file they fail. This is because the outcome of the seed changes. 

All you need to do is run `jest --watch` and update the hard coded expected values on the failing tests.

Once that's done, this is good to merge 😊

**Comment by theryansmee** [comment]
(Make sure to pull from main first, as it looks like some other foods have gone in)

**Comment by NetanelBasal** [comment]
@theryansmee can you merge and take care, please?

**Comment by theryansmee** [comment]
> @theryansmee can you merge and take care, please?

Yeah sure. Let me take a look now 😊

**Pull request merged**
